CREATE TABLE IF NOT EXISTS `sitepages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `site_url` varchar(128) NOT NULL,
  `title` varchar(128) NOT NULL,
  `text` text NOT NULL,
  `page_url` varchar(128) NOT NULL,
  `updated` datetime default NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

DROP TRIGGER IF EXISTS `SITE_PAGES_CREATE_TIMESTAMP`;
DELIMITER //
CREATE TRIGGER `SITE_PAGES_CREATE_TIMESTAMP` BEFORE INSERT ON `sitepages`
 FOR EACH ROW SET NEW.UPDATED = NOW()
//
DELIMITER ;

DROP TRIGGER IF EXISTS `SITE_PAGES_UPDATE_TIMESTAMP`;
DELIMITER //
CREATE TRIGGER `SITE_PAGES_UPDATE_TIMESTAMP` BEFORE UPDATE ON `sitepages`
 FOR EACH ROW SET NEW.UPDATED = NOW()
//
DELIMITER ;
